難易度選択ページ
Treasure-Hunting/Frontend pull request #10
Opened 2019-09-04 08:03 UTC by Ark-00

2019-09-04 09:44 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
ここは素直にGETだかPOSTだかで情報を投げるだけで問題ないと思います。難易度ごとにページを分ける必要はないと思います。

2019-09-05 03:12 UTC, Ark-00 commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
Django勉強してないのでよくわかんないんですけど、このページでpostして、次のページでgetするような感じになるような気がしたので、ページをわけて、postやgetを省こうと思いました。
そんな感じのめんどくさい記述にならないなら、難易度ごとで分けないですが。

2019-09-05 04:02 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
自分自身のURLを遷移先(及びPOST先)にすればよいかなと

2019-09-05 04:02 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
`<form action = "" method = "post">` みたいに

2019-09-05 04:03 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
そしたらバックで受け取ってもらえるかと

2019-09-05 13:10 UTC, Siketyan commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
ページ遷移で `form` 要素を使う理由ってなんですか? `a` 要素ではだめなんですか?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2019-09-05 14:51 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
えっと、最初の方で書きましたけど、冗長だと思ったので難易度の情報ごとにページを分けることをやめた方が(全ての難易度で同じページに遷移するようにした方が)良いかなと思いました。そのために、難易度情報を別の方法で得る必要がありますが、そのためにGETかPOSTを自分自身のページに送る必要があると思います。その例として`form`を使用することを提案してみたのです。

2019-09-05 14:54 UTC, Siketyan commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
session で得られるのでは?

2019-09-05 15:26 UTC, Snowman-s commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
これはまさにそのセッションに追加するための(プレイヤーに与える)難易度を選択するページだと思うのですが...。

2019-09-05 16:13 UTC, Siketyan commented on p2.html
> +        <button type="button" onclick="location.href='../p3-e/p3-e1.html'" name="dif">かんたん</button>
そういえばそうでした　黙ります

2019-09-07 08:02 UTC, Ark-00 commented
buttonタグをformタグの中に入れ、難易度ごとに、送信する値を設定しました。

2019-09-08 07:04 UTC, raiga0310 submitted a review, later dismissed
LGTM 👍

2019-09-08 08:54 UTC, Snowman-s requested changes
djangoの範囲が分かりませんが、以下の点をお願いします。

2019-09-08 08:54 UTC, Snowman-s commented on p2.html
> +        <form action="../p3-e/p3.js" method="post">
jsについて良く分かってなく、かつどこまでがBackendの仕事か分かりませんが、同じURLに飛ばす(`action=""`)ようにお願いします。また、postする場合には、djangoではセキュリティ上の理由により、`{% csrf_token %}` を`<form>`と `</form>`内に記述する必要があります。

2019-09-08 08:54 UTC, Snowman-s commented on p2.html
> +            <button onclick="location.href='../p3-e/p3.html'" name="easy" value="easy">かんたん</button>
form 内では、`<input>`タグを使用してください。

2019-09-08 08:55 UTC, Snowman-s commented on p2.html
> +        <form action="../p3-e/p3.js" method="post">
えっとつまり
```
<form>
    {% csrf_token %}
</form>
```
ということです。(中ならどこでもいいです。)

2019-09-08 14:22 UTC, Ark-00 commented on p2.html
> +        <form action="../p3-e/p3.js" method="post">
あ、すみません。なんかセキュリティに阻まれた段階でいろいろ実験してた残骸が残っているようです。
それがないからはじかれたのか...

2019-09-08 14:26 UTC, Ark-00 commented on p2.html
> +            <button onclick="location.href='../p3-e/p3.html'" name="easy" value="easy">かんたん</button>
inputのボタンと同じような感じらしいのですが、こちらではだめですかね？（ボタンタグのほうが使いやすい）

2019-09-09 07:32 UTC, Siketyan commented on p2.html
> +            <button onclick="location.href='../p3-e/p3.html'" name="easy" value="easy">かんたん</button>
`form` 内で `button` 要素を使ってはいけない旨の記述が調べた限り見つからなかったので，ソースを提示していただけると助かります．
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes

2019-09-09 08:01 UTC, Snowman-s commented on p2.html
> +            <button onclick="location.href='../p3-e/p3.html'" name="easy" value="easy">かんたん</button>
あ、すいません、なんか勘違いしてました。問題ないのかな？

2019-09-09 08:03 UTC, Siketyan commented on p2.html
> +            <button onclick="location.href='../p3-e/p3.html'" name="easy" value="easy">かんたん</button>
強いて言えば古いバージョンの Internet Explorer で不具合があるくらいみたいですね．
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/HTML_forms_in_legacy_browsers#Form_buttons

2019-09-10 10:11 UTC, siketyan requested changes

2019-09-10 10:11 UTC, Siketyan commented on Treasure/p2.html
> +</html>
```suggestion
</html>

```

2019-09-10 14:26 UTC, siketyan requested changes

2019-09-10 14:26 UTC, Siketyan commented on Treasure/p2.html
> +            <button onclick="location.href='../p3.html'" name="hard" value="hard">むずかしい</button> {% csrf_token %}
onclick で location.href を変えると何も POST されないと思います．

2019-09-12 01:06 UTC, raiga0310 commented
oursite/tresure/templates/tresure/dif_sel.html のように書けばとりあえず大丈夫だとは思いますが……。

2019-09-12 01:07 UTC, raiga0310 commented
https://github.com/Treasure-Hunting/Backend/blob/opening/oursite/tresure/views.py
これですね

2019-09-12 02:03 UTC, Siketyan commented on Treasure/p2.html
> +            <button onclick="location.href='../p3.html'" name="hard" value="hard">むずかしい</button> {% csrf_token %}
@Ark-00 未解決の問題を解決したとするのやめてもらえませんか．

2019-09-15 01:26 UTC, raiga0310 commented on Treasure/p2.html
> +            <button onclick="location.href='../p3.html'" name="hard" value="hard">むずかしい</button> {% csrf_token %}
`location.href='../p3.html'` から `href='/hints'` に変更するという感じで合っていますか

2019-09-17 12:14 UTC, Siketyan commented on Treasure/p2.html
> +            <button onclick="location.href='../p3.html'" name="hard" value="hard">むずかしい</button> {% csrf_token %}
いや，フォームで POST してください．

2019-09-17 12:50 UTC, raiga0310 commented on Treasure/p2.html
> +            <button onclick="location.href='../p3.html'" name="hard" value="hard">むずかしい</button> {% csrf_token %}
35cb8b7 でファイルを大幅に変更しました。このスレッドに伝えていなかったのは僕が怠ったせいです。すいません、あらためて確認お願いします

2019-09-17 12:55 UTC, You-0906 approved these changes

2019-09-17 13:01 UTC, siketyan approved these changes
結局フロントエンド部分もバックエンドが書いているなとはおもいました．

2019-09-17 13:01 UTC, merged