暗号を表示するページ
Treasure-Hunting/Frontend pull request #12
Opened 2019-09-04 08:28 UTC by Ark-00

2019-09-04 09:15 UTC, siketyan requested changes

2019-09-04 09:15 UTC, Siketyan commented on p4-e.html
> +</html>
Refs: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

```suggestion
</html>

```

2019-09-04 09:15 UTC, Siketyan commented on p4-e.html
> +    <meta name="viewport" content="width=device-width, intial-scale=1">
```suggestion
    <meta name="viewport" content="width=device-width, initial-scale=1">
```

2019-09-04 09:15 UTC, Siketyan commented on p4-e.html
> +    <meta charset="ufl-8" />
```suggestion
    <meta charset="utf-8" />
```

2019-09-04 09:38 UTC, Snowman-s commented on p4-e.html
> +        <div>00 00 00 00</div>
`00 00 00 00` はまだ名前が決定してないのが悪いですが `{{ [暗号が格納される変数名] }}` と書いていただけませんか。変数名は自由に決めてください。

2019-09-04 09:39 UTC, Siketyan commented on p4-e.html
> +        <div>00 00 00 00</div>
それは Vue.js や Mustache スタイルの表記では…？

2019-09-04 10:25 UTC, Snowman-s commented on p4-e.html
> +        <div>00 00 00 00</div>
いまいちよく分かってないのですが、ここでいうhtmlはtemplatesに突っ込むものだと思い込んでいます。で、djangoのtemplatesでは `{{ [変数名] }}` と記述するはずなのでこういうことを言ってます。

2019-09-04 10:26 UTC, Siketyan commented on p4-e.html
> +        <div>00 00 00 00</div>
なるほど，Django から注入する前提なんですね．理解しました．

2019-09-07 08:08 UTC, Ark-00 commented
Djangoから注入するどうこうがよくわかってないので、とりあえずｊｓで値いじれるようにidつけておきました。

2019-09-07 08:13 UTC, Ark-00 commented
とりあえず、パスワードを表示する欄のところを　{{[passward]}}　としておきました。

2019-09-08 07:06 UTC, raiga0310 approved these changes
LGTM 👍

2019-09-08 08:25 UTC, Snowman-s commented on p4-e.html
> +        <div>00 00 00 00</div>
ありがとうございます。

2019-09-08 08:27 UTC, Snowman-s commented
ファイルはきっと問題ありませんが、せっかくTresureフォルダが用意されてるので、その中に移してください。

2019-09-08 10:20 UTC, Snowman-s approved these changes
Looks Good To Me

2019-09-08 14:36 UTC, Ark-00 commented
ファイル移動ってどうすればいいの？

2019-09-09 07:46 UTC, Siketyan commented
@Ark-00 ファイルを移動すればいいかと思います．

2019-09-09 07:50 UTC, Snowman-s commented
自分のPC上で移動させてプッシュやコミットすればいいと思います。

2019-09-10 11:56 UTC, Snowman-s commented
僕がどんなに承認レビューしてもほぼ意味ないので、他の人にレビュー頼んで

2019-09-10 11:58 UTC, siketyan requested changes

2019-09-10 11:58 UTC, Siketyan commented on Treasure/p4.html
> +        <div id="pass">{{[passward]}}</div>
```suggestion
        <div id="pass">{{[password]}}</div>
```

2019-09-10 11:59 UTC, Siketyan commented
`{{ [foo] }}` ではなくて `{{ foo }}` では ?

2019-09-12 03:35 UTC, Snowman-s commented
ああ、確かに[] は必要ありませんでした。

2019-09-13 14:17 UTC, raiga0310 submitted a review, later dismissed

2019-09-13 14:17 UTC, raiga0310 commented on p4.html
> +        <div id="pass">{{[passward]}}</div>
{{ password }}ではないですか？

2019-09-13 16:58 UTC, raiga0310 commented on Treasure/p4.html
> +        <div>{{ code }}</div>
こういうことで合ってますか

2019-09-13 16:59 UTC, raiga0310 commented on Treasure/p4.html
> +        <div>{{ code }}</div>
18行目も同様の変更です

2019-09-15 01:31 UTC, raiga0310 reviewed
Aisgneeの僕自身がレビューするのもあれなので、別の人二人でレビューしておいてもらえると助かります

2019-09-15 01:37 UTC, raiga0310 commented
このページのBackendのページ名教えてください、自分では判断ができませんでした

2019-09-15 02:37 UTC, Siketyan commented
https://github.com/Treasure-Hunting/Backend/pull/26

2019-09-15 07:18 UTC, raiga0310 commented
変更しました、不備があれば教えてください

2019-09-15 11:29 UTC, You-0906 approved these changes
Looks Good To Me

2019-09-15 11:42 UTC, siketyan approved these changes

2019-09-15 11:48 UTC, merged