(Close #16)Reset
Treasure-Hunting/Frontend pull request #17
Opened 2019-09-18 15:26 UTC by raiga0310

refs. #16

2019-09-18 15:29 UTC, Siketyan commented on Treasure/reset.html
> +    <input type="radio" name="answer" value="n">いいえ
こういった破壊的変更を含む場合は否定のほうを既定にするべきかと思います．

2019-09-18 15:29 UTC, Siketyan commented on Treasure/reset.html
> +  <h1>現在のルートをあきらめて、スタートからやり直しますか？</h1>
この後に改めて元に戻せない旨を通知してもよさそうです．

2019-09-18 15:29 UTC, Siketyan commented on Treasure/style/reset.css
> +}
```suggestion
}

```

2019-09-18 15:43 UTC, raiga0310 commented
ChangeRequestの要請、すべて反映しました。問題なければレビュー改めてお願いします

2019-09-18 15:45 UTC, siketyan requested changes

2019-09-18 15:45 UTC, Siketyan commented on Treasure/reset.html
> +  <h3><div class="warning">警告</div>やり直しはもとに戻すことはできません。それを承知したうえで実行してください。<div class="warning">警告</div></h3>
`div` はインライン要素ではありません． `span` などを使用してください．

2019-09-18 15:46 UTC, raiga0310 commented on Treasure/reset.html
> +  <h3><div class="warning">警告</div>やり直しはもとに戻すことはできません。それを承知したうえで実行してください。<div class="warning">警告</div></h3>
はい

2019-09-18 15:50 UTC, raiga0310 commented
divからspanに変更しました。

2019-09-18 15:51 UTC, Siketyan commented
https://github.com/Treasure-Hunting/Frontend/pull/17/files#r325745303

2019-09-18 15:54 UTC, raiga0310 commented
なんか自分でレビューしていますが、押し間違えただけなので気にしないで下さい、LFは追加しました

2019-09-18 15:54 UTC, raiga0310 commented on Treasure/style/reset.css
> +}
上書きしていましたね。修正します。

2019-09-18 15:55 UTC, siketyan approved these changes

2019-09-19 13:37 UTC, You-0906 approved these changes

2019-09-19 13:37 UTC, merged