Hint answer separation
Treasure-Hunting/Frontend pull request #22
Opened 2019-10-16 01:41 UTC by raiga0310

SSIA

2019-10-16 03:10 UTC, Ark-00 approved these changes

2019-10-16 03:16 UTC, siketyan requested changes

2019-10-16 03:16 UTC, Siketyan commented on treasure/hints.html
> +    <button href = "https://treasure-hunting.tk/treasure/answer" name = "答えを入力する">
`button` 要素に `href` 属性はありません．
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

2019-10-16 03:16 UTC, Siketyan commented on treasure/go-goal.html
> +  {% ifequal diff_pk 1 %}
このファイルの diff は，この PR と関係ないように思えるのですが．

2019-10-16 03:16 UTC, Siketyan commented on treasure/answer.html
> +      <input type = "submit" value = "確認">
`key = value` の形式と `key=value` の形式とを統一してください．

2019-10-18 07:09 UTC, raiga0310 commented
指摘された点、変更しました

2019-10-22 23:48 UTC, Ark-00 approved these changes

2019-10-24 08:04 UTC, You-0906 approved these changes

2019-10-29 08:20 UTC, siketyan reviewed
answer.html と hints.html 以外の差分ってこの PR の内容に関係なくないですか?

2019-10-29 14:54 UTC, Snowman-s commented
`{%ifequal [数値リテラル] [数値リテラル]%}`

元のままでいいです。

2019-10-30 06:24 UTC, raiga0310 commented
このプルリクに関係のない修正を破棄、軽微な修正・コンフリクト解消を行いました。レビューお願いします

2019-10-30 06:24 UTC, Siketyan commented on treasure/hints.html
> +    <form action="" method="POST">
この差分ってこの PR に関係なくないですか?

2019-10-30 06:25 UTC, raiga0310 commented on treasure/hints.html
> +    <form action="" method="POST">
hintsを動作させる上では必要な修正だと思ったので入れたのですが……

2019-10-30 06:36 UTC, siketyan requested changes

2019-10-30 06:36 UTC, Siketyan commented on treasure/answer.html
> +    <script src="{% static "back-brevent.js" %}"></script>
```suggestion
    <script src="{% static "back-prevent.js" %}"></script>
```

2019-10-30 06:49 UTC, siketyan requested changes

2019-10-30 06:49 UTC, Siketyan commented on treasure/answer.html
> +      <input type="number">
1-4 以外の数値を指定できないように min と max を指定してはどうでしょうか．
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

2019-10-30 07:02 UTC, raiga0310 commented on treasure/answer.html
> +      <input type="number">
00~11の指定とのことなので、`select`タグでの選択形式にしました

2019-10-30 07:57 UTC, Snowman-s commented on treasure/answer.html
> +      <input type="number">
文字列指定してます

2019-10-30 07:58 UTC, Snowman-s commented on treasure/answer.html
> +      <input type="number">
Backendとしてはこのままでしか動作しないと思われます

2019-10-31 06:05 UTC, siketyan requested changes

2019-10-31 06:05 UTC, Siketyan commented on treasure/answer.html
> +      <select name="number" form="number" required>
親フォームの ID は設定されていないので form 属性は設定できません．
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

2019-10-31 06:12 UTC, siketyan reviewed
指摘分割してしまい申し訳ありません．
おそらくもうないです😣

2019-10-31 06:12 UTC, Siketyan commented on treasure/answer.html
> +    <title>input quiz answer</title>
タイトルがユーザフレンドリでない気がします．

2019-10-31 06:12 UTC, Siketyan commented on treasure/hints.html
> +    <h1>ヒント {{ hint_index }} / 4</h1>
hint_index って 1 オリジンですか?
把握してないので質問です🙇‍♂️

2019-10-31 06:34 UTC, raiga0310 commented on treasure/hints.html
> +    <h1>ヒント {{ hint_index }} / 4</h1>
らしいです(by @Snowman-s )

2019-10-31 06:45 UTC, siketyan approved these changes

2019-10-31 06:46 UTC, merged