Add files via upload
Treasure-Hunting/Frontend pull request #9
Opened 2019-09-04 07:58 UTC by Ark-00

2019-09-04 08:21 UTC, siketyan requested changes

2019-09-04 08:21 UTC, Siketyan commented on p1.html
> +    <meta name="viewport" content="width=device-width, intial-scale=1">
```suggestion
    <meta name="viewport" content="width=device-width, initial-scale=1">
```

2019-09-04 08:21 UTC, Siketyan commented on p1.html
> +    <meta charset="ufl-8" />
```suggestion
    <meta charset="utf-8">
```

2019-09-04 08:21 UTC, Siketyan commented on p1.html
> +</html>
```suggestion
</html>

```

2019-09-04 08:21 UTC, Siketyan commented on p1.html
> +            <div>・人に迷惑をかけない</div>
文書構造を意識して，適切な要素を選択してください．
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

2019-09-04 08:21 UTC, Siketyan commented on p1.html
> +        <button type="button" onclick="location.href='../p2/p2.html'" name="dif">次へ</button>
意味のある `name` 属性を設定してください．

2019-09-04 08:42 UTC, Ark-00 commented
指摘された箇所を訂正
注意事項のh2要素のdiv要素をli要素に変更
次へボタンのnameを"next"に変更

2019-09-04 08:51 UTC, siketyan requested changes

2019-09-04 08:51 UTC, Siketyan commented on p1.html
> +            <li>・人に迷惑をかけない</li>
> It must be contained in a parent element: an ordered list (`<ol>`), an unordered list (`<ul>`), or a menu (`<menu>`).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

2019-09-04 09:29 UTC, Snowman-s requested changes
Siketyanが既に指摘されているので、この部分を直していただければ問題ございません。

2019-09-04 09:29 UTC, Snowman-s commented on p1.html
> +            <li>・人に迷惑をかけない</li>
失礼ながら補足させていただきますと<li></li>タグは特定のタグに含める必要があります。今回の用途であれば、<ul></ul>タグが丸いと思います。

2019-09-07 08:00 UTC, Ark-00 commented
liタグをulタグの中に入れました。

2019-09-08 09:56 UTC, Snowman-s requested changes

2019-09-08 09:56 UTC, Snowman-s commented on p1.html
>          <button type="button" onclick="location.href='../p2/p2.html'" name="next">次へ</button>
余り個人的には良くないと思うのですが、仕様書通りに行えば自分自身のURLに押されたという情報をPOSTすることになると思います...。

2019-09-08 10:05 UTC, Snowman-s commented on p1.html
>          <button type="button" onclick="location.href='../p2/p2.html'" name="next">次へ</button>
またはdjangoの if文 と url文 を使用するか...。

2019-09-08 14:21 UTC, Ark-00 commented on p1.html
>          <button type="button" onclick="location.href='../p2/p2.html'" name="next">次へ</button>
なるほど。とりあえず、リハーサルの段階ではそれしなくても動きますかね？

2019-09-09 06:39 UTC, raiga0310 commented on p1.html
> +</html>
これ改行いる意味ってなんですか

2019-09-09 07:48 UTC, siketyan requested changes

2019-09-09 07:48 UTC, Siketyan commented on p1.html
> +        <ul>注意事項:
> 注意事項:

はリストの要素ではないので， `ul` 要素の中に記述しないでください．
（`ul` 要素の中身は `li` 要素の集合である必要があります．）

2019-09-09 07:48 UTC, Siketyan commented on p1.html
> +            <li></li>
不要な要素は削除してください．

2019-09-09 08:03 UTC, Snowman-s commented on p1.html
> +            <li></li>
削除には賛成ですが、
多分これは後々追加していくということを示しているんじゃないですかね...。
<!---->でコメント文として記述してください

2019-09-09 08:04 UTC, Snowman-s commented on p1.html
>          <button type="button" onclick="location.href='../p2/p2.html'" name="next">次へ</button>
んーまぁそうかも

2019-09-13 16:43 UTC, raiga0310 approved these changes
location.hrefのところはなんとも言えませんが僕としては特に問題はないかと思います。

2019-09-15 00:57 UTC, siketyan requested changes

2019-09-15 00:57 UTC, Siketyan commented on Treasure/p1.html
> +</html>
```suggestion
</html>

```

2019-09-15 01:07 UTC, siketyan approved these changes

2019-09-15 01:12 UTC, Siketyan commented
@raiga0310 マージしていいですか ?

2019-09-15 01:13 UTC, raiga0310 commented
はい、これで大丈夫です。

2019-09-15 01:13 UTC, merged

2019-09-15 01:13 UTC, raiga0310 commented
ありがとうございます。